import type { NextPage } from 'next'
import Head from 'next/head'
import ButtonAppBar from '../components/AppBar'
import Footer from '../components/Footer'
import Main from '../components/Main'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Crop Image Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ButtonAppBar />
      <Main />
      <Footer />
    </div>
  )
}

export default Home
